[package]
name = "honeybee"
version = "0.8.2"
authors = ["Douglas Lau <doug.lau@state.mn.us>"]
description = "Server for publishing IRIS data as JSON / GIF"
license = "GPL-2.0-or-later"
edition = "2018"

[dependencies]
base64 = "0.12.3"
fallible-iterator = "0.1"
gift = "0.9.1"
log = "0.4.8"
mag = "0.3.0"
ntcip = "0.4.1"
pix = "0.13.1"
postgres = "0.15.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
whoami = "0.8.1"

[dependencies.env_logger]
version = "0.7.1"
default-features = false
features = ["atty", "humantime"]
