[package]
name = "honeybee"
version = "0.7.0"
authors = ["Douglas Lau <doug.lau@state.mn.us>"]
description = "Server for publishing IRIS data as JSON / GIF"
license = "GPL-2.0-or-later"
edition = "2018"

[dependencies]
base64 = "0.11.0"
log = "0.4.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
fallible-iterator = "0.1"
ntcip = "0.1.2"
postgres = "0.15.2"
pix = "0.6.0"
gift = "0.3.1"
whoami = "0.5.3"

[dependencies.env_logger]
version = "0.7.0"
default-features = false
features = ["atty", "humantime"]
